version: '3.8'

services:
  app:
    build: ./
    command: ./go run server.go
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=qwerty123
      - DB_NAME=productdb
      - DB_HOST=db
      - DB_PORT=5432
      - PORT=8080
    ports:
      - 8080:8080

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: productdb
    ports:
      - 5432:5432
