// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID          string `json:"id"`
	Description string `json:"description"`
	Author      *User  `json:"author"`
	CreatedAt   string `json:"createdAt"`
}

type Mutation struct {
}

type NewComment struct {
	Description string `json:"description"`
	AuthorID    string `json:"authorId"`
	PostID      string `json:"postId"`
}

type NewPost struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	AuthorID    string `json:"authorId"`
	URL         string `json:"url"`
	Edit        bool   `json:"edit"`
}

type Post struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Author      *User      `json:"author"`
	URL         string     `json:"url"`
	Comments    []*Comment `json:"comments"`
	CreatedAt   string     `json:"createdAt"`
	Edit        bool       `json:"edit"`
}

type Query struct {
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
